/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexiones;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author Andres
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    
    String user="", update="";
    int id;
    public Modificar() {
        initComponents();
        user = Gestion.user;
        update = GestionPregunta.update;
        setSize(630, 450);
        setResizable(false);
        setTitle("Modificar pregunta.");
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection conec = con
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_pregunta = new javax.swing.JLabel();
        jLabel_pregunta1 = new javax.swing.JLabel();
        jLabel_pregunta2 = new javax.swing.JLabel();
        jLabel_pregunta3 = new javax.swing.JLabel();
        jLabel_pregunta4 = new javax.swing.JLabel();
        txt_respuesta = new javax.swing.JTextField();
        txt_falsa1 = new javax.swing.JTextField();
        txt_falsa2 = new javax.swing.JTextField();
        txt_falsa3 = new javax.swing.JTextField();
        txt_pregunta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel_pregunta5 = new javax.swing.JLabel();
        jLabel_pregunta6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel_pregunta.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pregunta.setText("Pregunta:");
        getContentPane().add(jLabel_pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel_pregunta1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pregunta1.setText("Respuesta");
        getContentPane().add(jLabel_pregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel_pregunta2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pregunta2.setText("Falsa 1");
        getContentPane().add(jLabel_pregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel_pregunta3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pregunta3.setText("Falsa 2:");
        getContentPane().add(jLabel_pregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel_pregunta4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pregunta4.setText("Falsa 3:");
        getContentPane().add(jLabel_pregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txt_respuesta.setBackground(new java.awt.Color(0, 0, 204));
        txt_respuesta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_respuesta.setForeground(new java.awt.Color(255, 255, 255));
        txt_respuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_respuesta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        txt_falsa1.setBackground(new java.awt.Color(0, 0, 204));
        txt_falsa1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_falsa1.setForeground(new java.awt.Color(255, 255, 255));
        txt_falsa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_falsa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_falsa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        txt_falsa2.setBackground(new java.awt.Color(0, 0, 204));
        txt_falsa2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_falsa2.setForeground(new java.awt.Color(255, 255, 255));
        txt_falsa2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_falsa2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_falsa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, -1));

        txt_falsa3.setBackground(new java.awt.Color(0, 0, 204));
        txt_falsa3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_falsa3.setForeground(new java.awt.Color(255, 255, 255));
        txt_falsa3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_falsa3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_falsa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, -1));

        txt_pregunta.setBackground(new java.awt.Color(0, 0, 204));
        txt_pregunta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_pregunta.setForeground(new java.awt.Color(255, 255, 255));
        txt_pregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pregunta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 550, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Historia", "Ciencia", "Entretenimiento", "Geografia", "Deportes" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 140, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ronda 1", "Ronda 2", "Ronda 3", "Ronda 4", "Ronda 5" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 140, 30));

        jLabel_pregunta5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pregunta5.setText("Categoria:");
        getContentPane().add(jLabel_pregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel_pregunta6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pregunta6.setText("Ronda:");
        getContentPane().add(jLabel_pregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar pregunta.");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 190, 90));

        jLabel_Wallpaper.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Wallpaper.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_pregunta;
    private javax.swing.JLabel jLabel_pregunta1;
    private javax.swing.JLabel jLabel_pregunta2;
    private javax.swing.JLabel jLabel_pregunta3;
    private javax.swing.JLabel jLabel_pregunta4;
    private javax.swing.JLabel jLabel_pregunta5;
    private javax.swing.JLabel jLabel_pregunta6;
    private javax.swing.JTextField txt_falsa1;
    private javax.swing.JTextField txt_falsa2;
    private javax.swing.JTextField txt_falsa3;
    private javax.swing.JTextField txt_pregunta;
    private javax.swing.JTextField txt_respuesta;
    // End of variables declaration//GEN-END:variables
}
